### ISSUE TITLE
Week 3(?) Code Review

### ISSUE THREAD

**Issue by siobhanmcgill** [Blak3Nick/jquery-apps#1]
I'm just taking a look at your code so far to see your progress through the Treehouse projects. I'm not sure the best way to send this information to you, so I'm trying out the Github Issues page on your repository so everything is in one place. If you would rather I just email you these updates, let me know.

Everything looks good so far! Some of the images on the simple lightbox app aren't loading for me when I cloned your repo to my computer. I doubt this is your fault, though. Your code works great, and that's what matters.

You seem to have a good grasp of everything so far. I doubt you'll have much trouble with anything Treehouse throws at you, but if you do have any questions about anything, feel free to reach out to me on Slack.

**Comment by siobhanmcgill** [comment]
Oh yeah, once you've gotten this you can feel free to Close it.

**Comment by Blak3Nick** [comment]
Thanks for the response! I am really enjoying the program so far.
